language: generic

script:
  # The only depencency: MarkdownPP.
  - pip install MarkdownPP --user
  # Build.
  - make
  # Deploy if needed.
  - bash ./deploy.sh

env:
  global:
    - ENCRYPTION_LABEL: "f8a585d5c928"
